#!/usr/local/bin/perl
#
# Use SNMP to cause an ascend box to tftp transfer its configuration
# to a save host.
#
# Uses these MIB entries:
#
#enterprises.ascend.systemStatusGroup.sysConfigTftp.sysConfigTftpCmd.0 = save(1)
#enterprises.ascend.systemStatusGroup.sysConfigTftp.sysConfigTftpStatus.0 = 1
#enterprises.ascend.systemStatusGroup.sysConfigTftp.sysConfigTftpHostAddr.0 = IpAddress: 0.0.0.0
#enterprises.ascend.systemStatusGroup.sysConfigTftp.sysConfigTftpFilename.0 = ""
#
# numeric equiv: .1.3.6.1.4.1.529.9.5

#$root = ".iso.org.dod.internet.private";
#$tftp = "enterprises.ascend.systemStatusGroup.sysConfigTftp";

use SNMP 1.6;

$ENV{'MIBDIRS'}="/usr/local/lib/snmp/mibs:/usr/local/lib/snmp/mibs/ascend";
$ENV{'MIBS'}="ALL";

$host=shift(@ARGV); # first arg is ascend box
$pwd=shift(@ARGV);  # 2nd arg is (R/W) community name

$savehost="rtfm";
$savefile="/export/tftpboot/ascend/$host";

if ($savehost =~ /^\s*((\d+\.){3}\d+)\s*$/)
   { $ip = pack ('C4', split (/\./, $1)) }
else
   { $ip = (gethostbyname($savehost))[4] }

return 0 unless $ip;		# "no such host"

$ip=unpack("N",$ip); #get back to an integer

#"touch" the save file. tftpd will not create it
open(FILE,">$savefile");
close(FILE);

#Now the nitty gritty
$session = new SNMP::Session (DestHost => $host, Version => 1,  Community => $pwd);

#setup the tftp target params
$new=$session->set("sysConfigTftpHostAddr.0",$ip);
$new=$session->set("sysConfigTftpFilename.0","$savefile");

#   save( 1 ),          -- save configuration             
#   restore( 2 ),       -- restore configuration          
#   saveAll( 3 ),       -- save ALL config options        
#   saveMib( 4 ),       -- save config w/MIB numbers      
#   saveAllMib( 5 ),    -- save ALL config w/MIB numbers  
#   loadCode( 6 )       -- load a code image              


#$new=$session->set("sysConfigTftpCmd.0",0x3); #start the save ALL
#$new=$session->get("sysConfigTftpStatus.0");  #wait till complete

if ( -z "$savefile"  ) {
#  print("Full save failed, trying a regular save.\n");
  $new=$session->set("sysConfigTftpCmd.0",0x1); #start the save config
  $new=$session->get("sysConfigTftpStatus.0");  #wait till complete
}

 #just to be nice, reset them to "clean" values
$new=$session->set("sysConfigTftpHostAddr.0",0); 
$new=$session->set("sysConfigTftpFilename.0","");
$new=$session->set("sysConfigTftpCmd.0",0x1);
$new=$session->get("sysConfigTftpStatus.0");


#check to make sure they're reset
$hadr=$session->get("sysConfigTftpHostAddr.0",0);
$fn=$session->get("sysConfigTftpFilename.0","");
$cmd=$session->get("sysConfigTftpCmd.0",0x1);
$new=$session->get("sysConfigTftpStatus.0");

print("Host: $hadr+0,  File: \"$fn\", Command: $cmd, Status $new\n");
